
-- copy into
COPY INTO BRONZE.CUSTOMERS
FROM @EXTERNAL_STAGE/customers/
ON_ERROR='CONTINUE';

COPY INTO BRONZE.PRODUCTS
FROM @EXTERNAL_STAGE/products/
ON_ERROR='CONTINUE';

COPY INTO BRONZE.ORDERS
FROM @EXTERNAL_STAGE/orders/
ON_ERROR='CONTINUE';

COPY INTO BRONZE.SHIPPERS
FROM @EXTERNAL_STAGE/shippers/
ON_ERROR='CONTINUE';

COPY INTO BRONZE.SUPPLIERS
FROM @EXTERNAL_STAGE/suppliers/
ON_ERROR='CONTINUE';

COPY INTO BRONZE.ORDER_DETAILS
FROM @EXTERNAL_STAGE/order_details/
ON_ERROR='CONTINUE';

COPY INTO BRONZE.CATEGORIES
FROM @EXTERNAL_STAGE/categories/
ON_ERROR='CONTINUE';

COPY INTO BRONZE.EMPLOYEES
FROM @EXTERNAL_STAGE/employees/
ON_ERROR='CONTINUE';


LIST @EXTERNAL_STAGE
DESC INTEGRATION NORTHWIND_S3_INTEG;


