
-- CUSTOMERS QULITY CHECK
SELECT * FROM BRONZE.CUSTOMERS; 

SELECT
    SUM(CASE WHEN COMPANY_NAME IS NULL OR TRIM(COMPANY_NAME)='' THEN 1 ELSE 0 END) AS NOISE_COMPANY_NAME,
    SUM(CASE WHEN CONTACT_NAME IS NULL OR TRIM(CONTACT_NAME)='' THEN 1 ELSE 0 END) AS NOISE_CONTACT_NAME,
    SUM(CASE WHEN COUNTRY IS NULL OR TRIM(COUNTRY)='' THEN 1 ELSE 0 END) AS NOISE_COUNTRY,
    SUM(CASE WHEN CITY IS NULL OR TRIM(CITY)='' THEN 1 ELSE 0 END) AS NOISE_CITY,
    SUM(CASE WHEN REGION IS NULL OR TRIM(REGION)='' OR TRIM(REGION)='NULL' THEN 1 ELSE 0 END) AS NOISE_REGION
FROM BRONZE.CUSTOMERS;



SELECT CUST_ID,COUNT(*) AS TOTAL_REPEAT
FROM BRONZE.CUSTOMERS
GROUP BY CUST_ID
HAVING COUNT(*) > 1;


SELECT * FROM SILVER.CUSTOMERS;

-- SUPPLIERS QULITY CHECK

SELECT 
    SUM(CASE WHEN COMPANY_NAME IS NULL OR TRIM(COMPANY_NAME)= 'NULL' OR TRIM(COMPANY_NAME) = ''  THEN 1 ELSE 0 END) AS NOISE_COMANY_NAME,
    SUM(CASE WHEN CONTACT_NAME IS NULL OR TRIM(CONTACT_NAME)= 'NULL' OR TRIM(CONTACT_NAME) = ''  THEN 1 ELSE 0 END) AS NOISE_CONTACT_NAME,
    SUM(CASE WHEN CONTACT_TITLE IS NULL OR TRIM(CONTACT_TITLE)= 'NULL' OR TRIM(CONTACT_TITLE) = ''  THEN 1 ELSE 0 END) AS NOISE_CONTACT_TITLE,
    SUM(CASE WHEN CITY IS NULL OR TRIM(CITY)= 'NULL' OR TRIM(CITY) = ''  THEN 1 ELSE 0 END) AS NOISE_CITY,
    SUM(CASE WHEN REGION IS NULL OR TRIM(REGION)= 'NULL' OR TRIM(REGION) = ''  THEN 1 ELSE 0 END) AS NOISE_REGION,
    SUM(CASE WHEN COUNTRY IS NULL OR TRIM(COUNTRY)= 'NULL' OR TRIM(COUNTRY) = ''  THEN 1 ELSE 0 END) AS NOISE_COUNTRY
FROM SUPPLIERS;

SELECT SUPPLIER_ID ,COUNT(*) AS TOTAL_REPEAT
FROM SUPPLIERS
GROUP BY SUPPLIER_ID
HAVING COUNT(*) > 1;


-- SHIPPERS QUALITY CHECK

SELECT * FROM BRONZE.SHIPPERS;

SELECT * FROM SILVER.SHIPPERS;

-- CATEGORIES QUALITY CHECK
SELECT * FROM BRONZE.CATEGORIES;

SELECT * FROM SILVER.CATEGORIES;

-- PRODUCTS QUALITY CHECK

SELECT * FROM BRONZE.PRODUCTS;

SELECT 
    SUM(CASE WHEN PROD_NAME IS NULL OR TRIM(PROD_NAME)='NULL' OR TRIM(PROD_NAME)='' THEN 1 ELSE 0  END) AS NOISE_PROD_NAME,
    SUM(CASE WHEN SUPPLIER_ID IS NULL OR TRIM(SUPPLIER_ID)='NULL' OR TRIM(SUPPLIER_ID)='' THEN 1 ELSE 0  END) AS NOISE_SUPPLIER_ID,
    SUM(CASE WHEN CATEGORY_ID IS NULL OR TRIM(CATEGORY_ID)='NULL' OR TRIM(CATEGORY_ID)='' THEN 1 ELSE 0  END) AS NOISE_CATEGORY_ID,
    SUM(CASE WHEN QUANTITY_PER_UNIT IS NULL OR TRIM(QUANTITY_PER_UNIT)='NULL' OR TRIM(QUANTITY_PER_UNIT)='' THEN 1 ELSE 0  END) AS NOISE_QUANT_PER_UNIT,
    SUM(CASE WHEN UNIT_PRICE IS NULL OR TRIM(UNIT_PRICE)='NULL' OR TRIM(UNIT_PRICE)='' THEN 1 ELSE 0  END) AS NOISE_UNIT_PRICE,
    SUM(CASE WHEN UNITS_IN_STOCK IS NULL OR TRIM(UNITS_IN_STOCK)='NULL' OR TRIM(UNITS_IN_STOCK)='' THEN 1 ELSE 0  END) AS NOISE_UNITS_IN_STOCK,
    SUM(CASE WHEN UNITS_ON_ORDER IS NULL OR TRIM(UNITS_ON_ORDER)='NULL' OR TRIM(UNITS_ON_ORDER)='' THEN 1 ELSE 0  END) AS NOISE_UNITS_ON_ORDER,
    SUM(CASE WHEN REORDER_LEVEL IS NULL OR TRIM(REORDER_LEVEL)='NULL' OR TRIM(REORDER_LEVEL)='' THEN 1 ELSE 0  END) AS NOISE_REORDER_LEVEL,
    SUM(CASE WHEN DISCOUNTED IS NULL OR TRIM(DISCOUNTED)='NULL' OR TRIM(DISCOUNTED)='' THEN 1 ELSE 0  END) AS NOISE_DISCOUNTED
FROM BRONZE.PRODUCTS;

SELECT PROD_ID,COUNT(*) AS REPEATED
FROM BRONZE.PRODUCTS
GROUP BY PROD_ID
HAVING COUNT(*)>1;

SELECT UNIT_PRICE,UNITS_IN_STOCK,UNITS_ON_ORDER 
FROM BRONZE.PRODUCTS     
WHERE UNIT_PRICE LIKE '-%' OR UNITS_IN_STOCK LIKE '-%' OR UNITS_ON_ORDER LIKE '-%';


SELECT * FROM SILVER.PRODUCTS;


-- ORDERS QUALITY CHECK

SELECT * FROM BRONZE.ORDERS;

SELECT 
    SUM(CASE WHEN ORDER_DATE IS NULL OR TRIM(ORDER_DATE)='NULL' OR TRIM(ORDER_DATE)='' THEN 1 ELSE 0 END) AS NOISE_ORDER_DATE,
    SUM(CASE WHEN REQUIRED_DATE IS NULL OR TRIM(REQUIRED_DATE)='NULL' OR TRIM(REQUIRED_DATE)='' THEN 1 ELSE 0 END) AS NOISE_REQUIRED_DATE,
    SUM(CASE WHEN SHIPPED_DATE IS NULL OR TRIM(SHIPPED_DATE)='NULL' OR TRIM(SHIPPED_DATE)='' THEN 1 ELSE 0 END) AS NOISE_SHIPPED_DATE,
    SUM(CASE WHEN FREIGHT IS NULL OR TRIM(FREIGHT)='NULL' OR TRIM(FREIGHT)='' THEN 1 ELSE 0 END) AS NOISE_FREIGHT,
    SUM(CASE WHEN SHIP_NAME IS NULL OR TRIM(SHIP_NAME)='NULL' OR TRIM(SHIP_NAME)='' THEN 1 ELSE 0 END) AS NOISE_SHIP_NAME,
    SUM(CASE WHEN SHIP_ADDRESS IS NULL OR TRIM(SHIP_ADDRESS)='NULL' OR TRIM(SHIP_ADDRESS)='' THEN 1 ELSE 0 END) AS NOISE_SHIP_ADDRESS,
    SUM(CASE WHEN SHIP_CITY IS NULL OR TRIM(SHIP_CITY)='NULL' OR TRIM(SHIP_CITY)='' THEN 1 ELSE 0 END) AS NOISE_SHIP_CITY,
    SUM(CASE WHEN SHIP_REGION IS NULL OR TRIM(SHIP_REGION)='NULL' OR TRIM(SHIP_REGION)='' THEN 1 ELSE 0 END) AS NOISE_SHIP_REGION,
    SUM(CASE WHEN SHIP_COUNTRY IS NULL OR TRIM(SHIP_COUNTRY)='NULL' OR TRIM(SHIP_COUNTRY)='' THEN 1 ELSE 0 END) AS NOISE_SHIP_COUNTRY

FROM BRONZE.ORDERS;

SELECT 
    ORDER_DATE ,
    REQUIRED_DATE,
    SHIPPED_DATE
FROM BRONZE.ORDERS
WHERE LENGTH(TRIM(ORDER_DATE)) != 8 OR LENGTH(TRIM(REQUIRED_DATE)) != 8 ;

SELECT ORDER_ID,COUNT(*) AS TOTAL_REPEAT
FROM BRONZE.ORDERS
GROUP BY ORDER_ID
HAVING COUNT(*) > 1;

SELECT * FROM SILVER.ORDERS;



-- ORDER_DETAILS QUALITY CHECK


SELECT * FROM BRONZE.ORDER_DETAILS;

SELECT 
    SUM(CASE WHEN ORDER_ID IS NULL OR TRIM(ORDER_ID)='NULL' OR TRIM(ORDER_ID)='' THEN 1 ELSE 0 END) AS NOISE_ORDER_ID,
    SUM(CASE WHEN PRODUCT_ID IS NULL OR TRIM(PRODUCT_ID)='NULL' OR TRIM(PRODUCT_ID)='' THEN 1 ELSE 0 END) AS NOISE_PRODUCT_ID,
    SUM(CASE WHEN UNIT_PRICE IS NULL OR TRIM(UNIT_PRICE)='NULL' OR TRIM(UNIT_PRICE)='' THEN 1 ELSE 0 END) AS NOISE_UNIT_PRICE,
    SUM(CASE WHEN QUANTITY IS NULL OR TRIM(QUANTITY)='NULL' OR TRIM(QUANTITY)='' THEN 1 ELSE 0 END) AS NOISE_QUANTITY,
    SUM(CASE WHEN DISCOUNT IS NULL OR TRIM(DISCOUNT)='NULL' OR TRIM(DISCOUNT)='' THEN 1 ELSE 0 END) AS NOISE_DISCOUNT
FROM BRONZE.ORDER_DETAILS;


select * from silver.order_details;
