SELECT 
    TRY_TO_NUMBER(EMP_ID) AS EMP_ID, -- YOU COULD USE CAST(EMP_ID AS INT) 
    (TRIM(FIRST_NAME)||' '||TRIM(LAST_NAME)) AS FULL_NAME, -- YOU COULD USE CONCAT()
    TRIM(TITLE) AS TITLE,
    TRIM(REPLACE(TITLE_OF_COURTESY,'.','')) AS TITLE_OF_COURTESY,
    {{ convert_date('BIRTH_DATE') }}AS BIRTH_DATE,
    {{ convert_date('HIRE_DATE') }} AS HIRE_DATE,  --CAST(TRIM(HIRE_DATE) AS DATE) YOU CAN USE THIS EXPRESSION BUT THE BEST IN ETL IS TRY TO DATE BECAUSE IF THERE ANY ERROR THE PROCESS WILL BE STOPPED IF WE USE CAST     
    TRIM(ADDRESS) AS ADDRESS,
    TRIM(CITY) AS CITY,
    {{ region_col_handling('REGION') }}AS REGION,
    TRIM(COUNTRY) AS COUNTRY
FROM {{source('bronze','EMPLOYEES')}}