SELECT 
    TRY_TO_NUMBER(TRIM(ORDER_ID)) AS ORDER_ID,
    TRIM(CUSTOMER_ID) AS CUSTOMER_ID,
    TRY_TO_NUMBER(TRIM(EMPLOYEE_ID)) AS EMPLOYEE_ID,

    {{ convert_date('ORDER_DATE') }} AS ORDER_DATE,
        
    {{ convert_date('REQUIRED_DATE') }} AS REQUIRED_DATE,

    {{ convert_date('SHIPPED_DATE') }} AS SHIPPED_DATE,

    TRY_TO_NUMBER(TRIM(SHIP_VIA)) AS SHIPPER_ID,
    TRY_TO_DECIMAL(TRIM(FREIGHT)) AS FREIGHT,
    TRIM(SHIP_NAME) AS SHIP_NAME,
    TRIM(SHIP_ADDRESS) SHIP_ADDRESS,
    TRIM(SHIP_CITY) AS SHIP_CITY,    
    {{ region_col_handling('SHIP_REGION') }}AS SHIP_REGION,
    TRIM(SHIP_COUNTRY) AS SHIP_COUNTRY

FROM {{source('bronze','ORDERS')}}