SELECT 
    TRY_TO_NUMBER(TRIM(ORDER_ID)) AS ORDER_ID,
    TRY_TO_NUMBER(TRIM(PRODUCT_ID)) AS PRODUCT_ID,
    TRY_TO_DECIMAL(TRIM(UNIT_PRICE)) AS UNIT_PRICE,
    TRY_TO_NUMBER(TRIM(QUANTITY)) AS QUANTITY,
    TRY_TO_DOUBLE(TRIM(DISCOUNT)) AS DISCOUNT

FROM {{source('bronze','ORDER_DETAILS')}}