SELECT 
    TRY_TO_NUMBER(TRIM(PROD_ID)) AS PROD_ID,
    TRIM(PROD_NAME) AS PROD_NAME,
    TRY_TO_NUMBER(TRIM(SUPPLIER_ID)) AS SUPPLIER_ID,
    TRY_TO_NUMBER(TRIM(CATEGORY_ID)) AS CATEGORY_ID,
    TRIM(QUANTITY_PER_UNIT) AS QUANTITY_PER_UNIT,
    TRY_TO_DECIMAL(TRIM(UNIT_PRICE)) AS UNIT_PRICE,
    TRY_TO_NUMBER(TRIM(UNITS_IN_STOCK)) AS UNITS_IN_STOCK,
    TRY_TO_NUMBER(TRIM(UNITS_ON_ORDER)) AS UNITS_ON_ORDER,
    TRY_TO_NUMBER(TRIM(REORDER_LEVEL)) AS REORDER_LEVEL,
    CASE
        WHEN TRIM(DISCOUNTED) = '1' THEN TRUE
        WHEN TRIM(DISCOUNTED) = '0' THEN FALSE
        ELSE NULL
    END AS IS_DISCOUNTED
    FROM {{source('bronze','PRODUCTS')}}