SELECT 
    TRY_TO_NUMBER(TRIM(SUPPLIER_ID)) AS SUPPLIER_ID,
    TRIM(COMPANY_NAME) AS COMPANY_NAME,
    TRIM(CONTACT_NAME) AS CONTACT_NAME,
    TRIM(CONTACT_TITLE) AS CONTACT_TITLE,
    TRIM(CITY) AS CITY,
    {{ region_col_handling('REGION') }}AS REGION,
    TRIM(COUNTRY) AS COUNTRY

FROM {{source('bronze','SUPPLIERS')}}