SELECT 
    ROW_NUMBER() OVER (ORDER BY PRODUCT.PROD_ID) AS PRODUCT_KEY,
    PRODUCT.PROD_ID,
    PRODUCT.PROD_NAME,
    CATEGORY.CATEGORY_NAME,
    SUPPLIER.COMPANY_NAME as SUPPLIER_COMPANY,
    SUPPLIER.COUNTRY as SUPPLIER_COUNTRY,
    SUPPLIER.CITY as SUPPLIER_CITY,
    PRODUCT.QUANTITY_PER_UNIT,
    PRODUCT.UNIT_PRICE,
    PRODUCT.UNITS_IN_STOCK,
    PRODUCT.UNITS_ON_ORDER,
    PRODUCT.REORDER_LEVEL,
    PRODUCT.IS_DISCOUNTED

    FROM {{ref('products')}} PRODUCT
    LEFT JOIN
    {{ref('categories')}} CATEGORY
    ON PRODUCT.CATEGORY_ID=CATEGORY.CATEGORY_ID
    LEFT JOIN 
    {{ref('suppliers')}} SUPPLIER
    ON PRODUCT.SUPPLIER_ID=SUPPLIER.SUPPLIER_ID